### ISSUE TITLE
Roasted Veggies don't get highlighted with Grill selected

### ISSUE THREAD

**Issue by LucoEldritch** [kleientertainment/TheGorgeRecipeBook#14]
Roasted Veggies can be created on Grill or Oven, but it only get highlighted with Oven filter marked.

**Comment by LucoEldritch** [comment]
Created pull request at #15

**Comment by cheewind** [comment]
Yah.....I didn't notice roasted veggies can be cooked on two stations when I write line #155.
Thank you for notice it

**Comment by cheewind** [comment]
at least ...... I left a comment there that time

**Comment by ricardjorg** [comment]
@LucoEldritch Thanks for the fix! It's in now. You're awesome!
